from enum import Enum


class StringEnum(str, Enum):
    pass


class UserRole(StringEnum):
    OPERATOR = "OPERATOR"
    SUPERVISOR = "SUPERVISOR"


class PalletStatus(StringEnum):
    AVAILABLE = "AVAILABLE"
    RESERVED = "RESERVED"
    DISPATCHED = "DISPATCHED"
    BLOCKED = "BLOCKED"


class InspectionStatus(StringEnum):
    IN_PROGRESS = "IN_PROGRESS"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"


class ObservedState(StringEnum):
    PALLET = "PALLET"
    EMPTY = "EMPTY"
    UNRESOLVED = "UNRESOLVED"


class ReadingStatus(StringEnum):
    ACCEPTED = "ACCEPTED"
    RESCAN_REQUIRED = "RESCAN_REQUIRED"
    HUMAN_REVIEW_REQUIRED = "HUMAN_REVIEW_REQUIRED"


class ComparisonResult(StringEnum):
    CORRECT = "CORRECT"
    PALLET_MISMATCH = "PALLET_MISMATCH"
    CORRECT_EMPTY = "CORRECT_EMPTY"
    UNEXPECTED_PALLET = "UNEXPECTED_PALLET"
    EXPECTED_PALLET_MISSING = "EXPECTED_PALLET_MISSING"
    UNRESOLVED = "UNRESOLVED"


class ExceptionType(StringEnum):
    PALLET_MISMATCH = "PALLET_MISMATCH"
    PALLET_MISSING = "PALLET_MISSING"
    UNEXPECTED_PALLET = "UNEXPECTED_PALLET"
    LOW_QUALITY = "LOW_QUALITY"
    EXPIRING_SOON = "EXPIRING_SOON"
    HIGH_ROTATION = "HIGH_ROTATION"
    LOW_COVERAGE = "LOW_COVERAGE"
    FEFO_RISK = "FEFO_RISK"
    HISTORICAL_ANOMALY = "HISTORICAL_ANOMALY"


class ExceptionStatus(StringEnum):
    OPEN = "OPEN"
    IN_REVIEW = "IN_REVIEW"
    RESOLVED = "RESOLVED"


class Severity(StringEnum):
    INFO = "INFO"
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class SourceType(StringEnum):
    ANDROID_CAMERA = "ANDROID_CAMERA"
    MANUAL_DEMO = "MANUAL_DEMO"
    DRONE = "DRONE"
    MANUAL = "MANUAL"
    SEED_SYSTEM = "SEED_SYSTEM"
    WMS_IMPORT = "WMS_IMPORT"


class EvidenceType(StringEnum):
    ORIGINAL = "ORIGINAL"
    RESCAN = "RESCAN"
    EMPTY_CONFIRMATION = "EMPTY_CONFIRMATION"
    MANUAL_REVIEW = "MANUAL_REVIEW"


class MovementType(StringEnum):
    INBOUND = "INBOUND"
    OUTBOUND = "OUTBOUND"
    TRANSFER = "TRANSFER"
    ADJUSTMENT = "ADJUSTMENT"


class FlowTwinChangeType(StringEnum):
    # PALLET_ADDED is retained as a legacy storage value; UI/API call it "Pallet apareció".
    PALLET_ADDED = "PALLET_ADDED"
    PALLET_REMOVED = "PALLET_REMOVED"
    PALLET_CHANGED = "PALLET_CHANGED"
    RESULT_CHANGED = "RESULT_CHANGED"
    BECAME_UNRESOLVED = "BECAME_UNRESOLVED"
    RESOLVED_SINCE_PREVIOUS = "RESOLVED_SINCE_PREVIOUS"
    EXPECTED_CHANGED = "EXPECTED_CHANGED"
    PERSISTENT_DISCREPANCY = "PERSISTENT_DISCREPANCY"
    AUTHORIZED_MOVEMENT = "AUTHORIZED_MOVEMENT"


class ResolutionType(StringEnum):
    CONFIRMED = "CONFIRMED"
    CORRECTED = "CORRECTED"
    FALSE_POSITIVE = "FALSE_POSITIVE"
