"""initial_schema

Revision ID: 75895c0372ab
Revises: 
Create Date: 2026-09-19 23:50:12.727969
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '75895c0372ab'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('sku', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('unit', sa.String(length=40), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_products')),
    sa.UniqueConstraint('sku', name=op.f('uq_products_sku'))
    )
    op.create_table('users',
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=160), nullable=False),
    sa.Column('role', sa.Enum('OPERATOR', 'SUPERVISOR', name='user_role', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('username', name=op.f('uq_users_username'))
    )
    op.create_table('warehouse_zones',
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_warehouse_zones')),
    sa.UniqueConstraint('code', name=op.f('uq_warehouse_zones_code'))
    )
    op.create_table('agent_query_logs',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('tool_called', sa.String(length=100), nullable=True),
    sa.Column('response', sa.Text(), nullable=False),
    sa.Column('fallback_used', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.CheckConstraint('latency_ms IS NULL OR latency_ms >= 0', name=op.f('ck_agent_query_logs_latency_non_negative')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_agent_query_logs_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_query_logs'))
    )
    op.create_index(op.f('ix_agent_query_logs_user_id'), 'agent_query_logs', ['user_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_audit_logs_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index(op.f('ix_audit_logs_event_type'), 'audit_logs', ['event_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('inspections',
    sa.Column('zone_id', sa.Integer(), nullable=False),
    sa.Column('started_by', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='inspection_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['started_by'], ['users.id'], name=op.f('fk_inspections_started_by_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['zone_id'], ['warehouse_zones.id'], name=op.f('fk_inspections_zone_id_warehouse_zones'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inspections'))
    )
    op.create_index(op.f('ix_inspections_zone_id'), 'inspections', ['zone_id'], unique=False)
    op.create_table('locations',
    sa.Column('zone_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('row_index', sa.Integer(), nullable=False),
    sa.Column('column_index', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('column_index >= 1', name=op.f('ck_locations_column_index_positive')),
    sa.CheckConstraint('level >= 1 AND level <= 20', name=op.f('ck_locations_level_reasonable')),
    sa.CheckConstraint('row_index >= 1', name=op.f('ck_locations_row_index_positive')),
    sa.ForeignKeyConstraint(['zone_id'], ['warehouse_zones.id'], name=op.f('fk_locations_zone_id_warehouse_zones'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_locations')),
    sa.UniqueConstraint('code', name=op.f('uq_locations_code'))
    )
    op.create_index(op.f('ix_locations_zone_id'), 'locations', ['zone_id'], unique=False)
    op.create_table('lots',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('lot_code', sa.String(length=50), nullable=False),
    sa.Column('manufactured_at', sa.Date(), nullable=False),
    sa.Column('expires_at', sa.Date(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('expires_at > manufactured_at', name=op.f('ck_lots_expiry_after_manufacture')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_lots_product_id_products'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lots')),
    sa.UniqueConstraint('lot_code', name=op.f('uq_lots_lot_code'))
    )
    op.create_index(op.f('ix_lots_expires_at'), 'lots', ['expires_at'], unique=False)
    op.create_index(op.f('ix_lots_product_id'), 'lots', ['product_id'], unique=False)
    op.create_table('pallets',
    sa.Column('pallet_code', sa.String(length=50), nullable=False),
    sa.Column('lot_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('AVAILABLE', 'RESERVED', 'DISPATCHED', 'BLOCKED', name='pallet_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('quantity >= 0', name=op.f('ck_pallets_quantity_non_negative')),
    sa.ForeignKeyConstraint(['lot_id'], ['lots.id'], name=op.f('fk_pallets_lot_id_lots'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pallets')),
    sa.UniqueConstraint('pallet_code', name=op.f('uq_pallets_pallet_code'))
    )
    op.create_index(op.f('ix_pallets_lot_id'), 'pallets', ['lot_id'], unique=False)
    op.create_table('expected_inventory',
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('expected_pallet_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['expected_pallet_id'], ['pallets.id'], name=op.f('fk_expected_inventory_expected_pallet_id_pallets'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], name=op.f('fk_expected_inventory_location_id_locations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_expected_inventory')),
    sa.UniqueConstraint('expected_pallet_id', name=op.f('uq_expected_inventory_expected_pallet_id')),
    sa.UniqueConstraint('location_id', name=op.f('uq_expected_inventory_location_id'))
    )
    op.create_table('flowtwin_changes',
    sa.Column('current_inspection_id', sa.Integer(), nullable=False),
    sa.Column('previous_inspection_id', sa.Integer(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('change_type', sa.Enum('PALLET_ADDED', 'PALLET_REMOVED', 'PALLET_CHANGED', 'RESULT_CHANGED', name='flowtwin_change_type', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('previous_pallet_id', sa.Integer(), nullable=True),
    sa.Column('current_pallet_id', sa.Integer(), nullable=True),
    sa.Column('previous_result', sa.Enum('MATCH', 'PALLET_MISMATCH', 'EXPECTED_EMPTY', 'UNEXPECTED_PALLET', 'EXPECTED_PALLET_MISSING', 'UNVERIFIED', name='flowtwin_previous_result', native_enum=False, create_constraint=True), nullable=True),
    sa.Column('current_result', sa.Enum('MATCH', 'PALLET_MISMATCH', 'EXPECTED_EMPTY', 'UNEXPECTED_PALLET', 'EXPECTED_PALLET_MISSING', 'UNVERIFIED', name='flowtwin_current_result', native_enum=False, create_constraint=True), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['current_inspection_id'], ['inspections.id'], name=op.f('fk_flowtwin_changes_current_inspection_id_inspections'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['current_pallet_id'], ['pallets.id'], name=op.f('fk_flowtwin_changes_current_pallet_id_pallets'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], name=op.f('fk_flowtwin_changes_location_id_locations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['previous_inspection_id'], ['inspections.id'], name=op.f('fk_flowtwin_changes_previous_inspection_id_inspections'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['previous_pallet_id'], ['pallets.id'], name=op.f('fk_flowtwin_changes_previous_pallet_id_pallets'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_flowtwin_changes'))
    )
    op.create_index(op.f('ix_flowtwin_changes_current_inspection_id'), 'flowtwin_changes', ['current_inspection_id'], unique=False)
    op.create_index(op.f('ix_flowtwin_changes_location_id'), 'flowtwin_changes', ['location_id'], unique=False)
    op.create_table('inspection_readings',
    sa.Column('inspection_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('client_reading_id', sa.Uuid(), nullable=False),
    sa.Column('reading_group_id', sa.Uuid(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('expected_pallet_id_at_inspection', sa.Integer(), nullable=True),
    sa.Column('observed_pallet_id', sa.Integer(), nullable=True),
    sa.Column('observed_state', sa.Enum('PALLET', 'EMPTY', 'UNREADABLE', name='observed_state', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('quality_score', sa.Integer(), nullable=False),
    sa.Column('reading_status', sa.Enum('ACCEPTED', 'REQUIRES_RESCAN', 'REJECTED', name='reading_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('comparison_result', sa.Enum('MATCH', 'PALLET_MISMATCH', 'EXPECTED_EMPTY', 'UNEXPECTED_PALLET', 'EXPECTED_PALLET_MISSING', 'UNVERIFIED', name='comparison_result', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('is_final', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.Enum('ANDROID_CAMERA', 'MANUAL', 'SEED_SYSTEM', 'WMS_IMPORT', name='source_type', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('empty_confirmed_by_operator', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.CheckConstraint('attempt_number >= 1', name=op.f('ck_inspection_readings_attempt_number_positive')),
    sa.CheckConstraint('quality_score >= 0 AND quality_score <= 100', name=op.f('ck_inspection_readings_quality_score_range')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_inspection_readings_created_by_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['expected_pallet_id_at_inspection'], ['pallets.id'], name=op.f('fk_inspection_readings_expected_pallet_id_at_inspection_pallets'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], name=op.f('fk_inspection_readings_inspection_id_inspections'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], name=op.f('fk_inspection_readings_location_id_locations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['observed_pallet_id'], ['pallets.id'], name=op.f('fk_inspection_readings_observed_pallet_id_pallets'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inspection_readings')),
    sa.UniqueConstraint('client_reading_id', name=op.f('uq_inspection_readings_client_reading_id'))
    )
    op.create_index(op.f('ix_inspection_readings_inspection_id'), 'inspection_readings', ['inspection_id'], unique=False)
    op.create_index(op.f('ix_inspection_readings_location_id'), 'inspection_readings', ['location_id'], unique=False)
    op.create_index('uq_inspection_readings_final_group', 'inspection_readings', ['inspection_id', 'location_id', 'reading_group_id'], unique=True, postgresql_where=sa.text('is_final = true'))
    op.create_table('movement_history',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('lot_id', sa.Integer(), nullable=True),
    sa.Column('pallet_id', sa.Integer(), nullable=True),
    sa.Column('movement_type', sa.Enum('INBOUND', 'OUTBOUND', 'TRANSFER', 'ADJUSTMENT', name='movement_type', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_zone_id', sa.Integer(), nullable=True),
    sa.Column('destination_zone_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_movement_history_quantity_positive')),
    sa.ForeignKeyConstraint(['destination_zone_id'], ['warehouse_zones.id'], name=op.f('fk_movement_history_destination_zone_id_warehouse_zones'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lot_id'], ['lots.id'], name=op.f('fk_movement_history_lot_id_lots'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['pallet_id'], ['pallets.id'], name=op.f('fk_movement_history_pallet_id_pallets'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_movement_history_product_id_products'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_zone_id'], ['warehouse_zones.id'], name=op.f('fk_movement_history_source_zone_id_warehouse_zones'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_movement_history'))
    )
    op.create_index(op.f('ix_movement_history_lot_id'), 'movement_history', ['lot_id'], unique=False)
    op.create_index(op.f('ix_movement_history_movement_type'), 'movement_history', ['movement_type'], unique=False)
    op.create_index(op.f('ix_movement_history_occurred_at'), 'movement_history', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_movement_history_pallet_id'), 'movement_history', ['pallet_id'], unique=False)
    op.create_index(op.f('ix_movement_history_product_id'), 'movement_history', ['product_id'], unique=False)
    op.create_table('evidence_files',
    sa.Column('reading_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('source_type', sa.Enum('ANDROID_CAMERA', 'MANUAL', 'SEED_SYSTEM', 'WMS_IMPORT', name='evidence_source_type', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('evidence_type', sa.Enum('PALLET_READING', 'EMPTY_CONFIRMATION', 'LOCATION_READING', name='evidence_type', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('checksum', sa.String(length=128), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.CheckConstraint('height IS NULL OR height > 0', name=op.f('ck_evidence_files_height_positive')),
    sa.CheckConstraint('width IS NULL OR width > 0', name=op.f('ck_evidence_files_width_positive')),
    sa.ForeignKeyConstraint(['reading_id'], ['inspection_readings.id'], name=op.f('fk_evidence_files_reading_id_inspection_readings'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evidence_files')),
    sa.UniqueConstraint('file_path', name=op.f('uq_evidence_files_file_path'))
    )
    op.create_index(op.f('ix_evidence_files_reading_id'), 'evidence_files', ['reading_id'], unique=False)
    op.create_table('exception_events',
    sa.Column('inspection_id', sa.Integer(), nullable=True),
    sa.Column('reading_id', sa.Integer(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('pallet_id', sa.Integer(), nullable=True),
    sa.Column('exception_type', sa.Enum('PALLET_MISMATCH', 'PALLET_MISSING', 'UNEXPECTED_PALLET', 'LOW_QUALITY', 'EXPIRING_SOON', 'HIGH_ROTATION', 'LOW_COVERAGE', 'FEFO_RISK', 'HISTORICAL_ANOMALY', name='exception_type', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('severity', sa.Enum('INFO', 'LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='severity', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'IN_REVIEW', 'RESOLVED', name='exception_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('risk_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('resolution_type', sa.Enum('CONFIRMED', 'CORRECTED', 'FALSE_POSITIVE', name='resolution_type', native_enum=False, create_constraint=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by', sa.Integer(), nullable=True),
    sa.Column('resolution_comment', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.CheckConstraint('risk_score >= 0 AND risk_score <= 100', name=op.f('ck_exception_events_risk_score_range')),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], name=op.f('fk_exception_events_inspection_id_inspections'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], name=op.f('fk_exception_events_location_id_locations'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['pallet_id'], ['pallets.id'], name=op.f('fk_exception_events_pallet_id_pallets'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_exception_events_product_id_products'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reading_id'], ['inspection_readings.id'], name=op.f('fk_exception_events_reading_id_inspection_readings'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], name=op.f('fk_exception_events_resolved_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exception_events'))
    )
    op.create_index(op.f('ix_exception_events_inspection_id'), 'exception_events', ['inspection_id'], unique=False)
    op.create_index(op.f('ix_exception_events_location_id'), 'exception_events', ['location_id'], unique=False)
    op.create_index(op.f('ix_exception_events_pallet_id'), 'exception_events', ['pallet_id'], unique=False)
    op.create_index(op.f('ix_exception_events_product_id'), 'exception_events', ['product_id'], unique=False)
    op.create_index(op.f('ix_exception_events_reading_id'), 'exception_events', ['reading_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exception_events_reading_id'), table_name='exception_events')
    op.drop_index(op.f('ix_exception_events_product_id'), table_name='exception_events')
    op.drop_index(op.f('ix_exception_events_pallet_id'), table_name='exception_events')
    op.drop_index(op.f('ix_exception_events_location_id'), table_name='exception_events')
    op.drop_index(op.f('ix_exception_events_inspection_id'), table_name='exception_events')
    op.drop_table('exception_events')
    op.drop_index(op.f('ix_evidence_files_reading_id'), table_name='evidence_files')
    op.drop_table('evidence_files')
    op.drop_index(op.f('ix_movement_history_product_id'), table_name='movement_history')
    op.drop_index(op.f('ix_movement_history_pallet_id'), table_name='movement_history')
    op.drop_index(op.f('ix_movement_history_occurred_at'), table_name='movement_history')
    op.drop_index(op.f('ix_movement_history_movement_type'), table_name='movement_history')
    op.drop_index(op.f('ix_movement_history_lot_id'), table_name='movement_history')
    op.drop_table('movement_history')
    op.drop_index('uq_inspection_readings_final_group', table_name='inspection_readings', postgresql_where=sa.text('is_final = true'))
    op.drop_index(op.f('ix_inspection_readings_location_id'), table_name='inspection_readings')
    op.drop_index(op.f('ix_inspection_readings_inspection_id'), table_name='inspection_readings')
    op.drop_table('inspection_readings')
    op.drop_index(op.f('ix_flowtwin_changes_location_id'), table_name='flowtwin_changes')
    op.drop_index(op.f('ix_flowtwin_changes_current_inspection_id'), table_name='flowtwin_changes')
    op.drop_table('flowtwin_changes')
    op.drop_table('expected_inventory')
    op.drop_index(op.f('ix_pallets_lot_id'), table_name='pallets')
    op.drop_table('pallets')
    op.drop_index(op.f('ix_lots_product_id'), table_name='lots')
    op.drop_index(op.f('ix_lots_expires_at'), table_name='lots')
    op.drop_table('lots')
    op.drop_index(op.f('ix_locations_zone_id'), table_name='locations')
    op.drop_table('locations')
    op.drop_index(op.f('ix_inspections_zone_id'), table_name='inspections')
    op.drop_table('inspections')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_event_type'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_agent_query_logs_user_id'), table_name='agent_query_logs')
    op.drop_table('agent_query_logs')
    op.drop_table('warehouse_zones')
    op.drop_table('users')
    op.drop_table('products')
    # ### end Alembic commands ###

